<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAPTOP-OFVKRPE8" failures="2" tests="9" name="Firefox Tests" time="1083.554" errors="0" timestamp="2025-09-13T23:13:00 IST">
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="invalidLoginTest" time="42.045"/>
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="invalidLoginTest" time="41.965"/>
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="validLoginTest" time="41.98">
    <skipped/>
  </testcase> <!-- validLoginTest -->
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="validLoginTest" time="42.063">
    <skipped/>
  </testcase> <!-- validLoginTest -->
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="validLoginTest" time="41.992">
    <failure type="java.lang.AssertionError" message="Login method returned false for: user1@test expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login method returned false for: user1@test expected [true] but found [false]
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- validLoginTest -->
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="validLoginTest" time="41.986">
    <skipped/>
  </testcase> <!-- validLoginTest -->
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="validLoginTest" time="41.967">
    <skipped/>
  </testcase> <!-- validLoginTest -->
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="validLoginTest" time="42.05">
    <failure type="java.lang.AssertionError" message="Login method returned false for: user2@test expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login method returned false for: user2@test expected [true] but found [false]
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- validLoginTest -->
  <testcase classname="ramchavantestautomation.Tests.SampleUnitTest" name="alwaysPass" time="0.006"/>
  <testcase classname="ramchavantestautomation.Tests.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="ramchavantestautomation.Tests.BaseTest" name="@BeforeSuite setUpSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setUpSuite -->
</testsuite> <!-- Firefox Tests -->
