<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAPTOP-OFVKRPE8" failures="2" tests="9" name="Chrome Tests" time="1012.087" errors="0" timestamp="2025-09-14T01:05:46 IST">
  <testcase classname="ramchavantestautomation.Tests.BaseTest" name="@AfterMethod captureResult" time="0.002">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;ramchavantestautomation.WebActions.WebAction.captureScreenshot(String)&amp;quot; because &amp;quot;this.action&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "ramchavantestautomation.WebActions.WebAction.captureScreenshot(String)" because "this.action" is null
at ramchavantestautomation.Tests.BaseTest.captureResult(BaseTest.java:84)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod captureResult -->
  <testcase classname="ramchavantestautomation.Tests.BaseTest" name="@AfterMethod captureResult" time="0.001">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;ramchavantestautomation.WebActions.WebAction.captureScreenshot(String)&amp;quot; because &amp;quot;this.action&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "ramchavantestautomation.WebActions.WebAction.captureScreenshot(String)" because "this.action" is null
at ramchavantestautomation.Tests.BaseTest.captureResult(BaseTest.java:84)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod captureResult -->
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="invalidLoginTest" time="42.908"/>
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="invalidLoginTest" time="42.916"/>
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="validLoginTest" time="42.9">
    <skipped/>
  </testcase> <!-- validLoginTest -->
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="validLoginTest" time="43.009">
    <skipped/>
  </testcase> <!-- validLoginTest -->
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="validLoginTest" time="43.008">
    <failure type="java.lang.AssertionError" message="Login method returned false for: user1@test expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login method returned false for: user1@test expected [true] but found [false]
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- validLoginTest -->
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="validLoginTest" time="43.034">
    <skipped/>
  </testcase> <!-- validLoginTest -->
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="validLoginTest" time="43.079">
    <skipped/>
  </testcase> <!-- validLoginTest -->
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="validLoginTest" time="43.103">
    <failure type="java.lang.AssertionError" message="Login method returned false for: user2@test expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login method returned false for: user2@test expected [true] but found [false]
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- validLoginTest -->
  <testcase classname="ramchavantestautomation.Tests.SampleUnitTest" name="alwaysPass" time="0.008"/>
  <testcase classname="ramchavantestautomation.Tests.BaseTest" name="@BeforeSuite setUpSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setUpSuite -->
  <testcase classname="ramchavantestautomation.Tests.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
</testsuite> <!-- Chrome Tests -->
