<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAPTOP-OFVKRPE8" failures="2" tests="9" name="Firefox Tests" time="1077.055" errors="0" timestamp="2025-09-14T01:06:51 IST">
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="invalidLoginTest" time="43.024"/>
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="invalidLoginTest" time="43.033"/>
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="validLoginTest" time="43.025">
    <skipped/>
  </testcase> <!-- validLoginTest -->
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="validLoginTest" time="43.02">
    <skipped/>
  </testcase> <!-- validLoginTest -->
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="validLoginTest" time="43.094">
    <failure type="java.lang.AssertionError" message="Login method returned false for: user1@test expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login method returned false for: user1@test expected [true] but found [false]
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- validLoginTest -->
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="validLoginTest" time="42.998">
    <skipped/>
  </testcase> <!-- validLoginTest -->
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="validLoginTest" time="42.998">
    <skipped/>
  </testcase> <!-- validLoginTest -->
  <testcase classname="ramchavantestautomation.Tests.LoginPageTest" name="validLoginTest" time="42.975">
    <failure type="java.lang.AssertionError" message="Login method returned false for: user2@test expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login method returned false for: user2@test expected [true] but found [false]
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- validLoginTest -->
  <testcase classname="ramchavantestautomation.Tests.SampleUnitTest" name="alwaysPass" time="0.0"/>
  <testcase classname="ramchavantestautomation.Tests.BaseTest" name="@BeforeSuite setUpSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setUpSuite -->
  <testcase classname="ramchavantestautomation.Tests.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
</testsuite> <!-- Firefox Tests -->
